### ISSUE TITLE
Crash on world load with Ender IO

### ISSUE THREAD

**Issue by Anarcraft** [Chisel-2/Chisel-2#100]
Chisel 2-2.2.1 and EnderIO-1.7.10-2.2.6.317

http://pastebin.com/383x5Gqj

**Comment by Anarcraft** [comment]
Now I'm not having this issue after updating many mods in my pack but EIO isn't one of them.  A list of the mods I updated: (version 1.0.2) https://docs.google.com/document/d/1tGnnhNFeX2LHgrQ130CFzNJuptPHyx3n7WxD6OgEdiI

**Comment by warlordjones** [comment]
Should be fixed.
