### ISSUE TITLE
Wood and Glass tooltips not translatable

### ISSUE THREAD

**Issue by Adaptivity** [Chisel-2/Chisel-2#103]
For proper they all should be moved one by one. Not just one word "Smooth"(and other adjectives) for all wood planks. Colors should be splitted: 16 colors for glass and 16 colors for panels.

**Comment by TheCricket** [comment]
I can work out a fix tonight

**Comment by Adaptivity** [comment]
Anything about it?

**Comment by TheCricket** [comment]
done

**Comment by warlordjones** [comment]
Nope, issues should only be closed when the release with the fix in is made.

**Comment by Adaptivity** [comment]
lol? New release just out on curse.
