### ISSUE TITLE
Feature Requests: Chiselable Beacon, and Ender Voidstone.

### ISSUE THREAD

**Issue by Rious** [Chisel-2/Chisel-2#120]
Some suggestions

- Beacon, I'd like to see some variatons of this. (broken down, overgrown, perhaps different colors.. etc)

- A block much like the void stone, but uses the enderchest inside textures. Much like the lava\water stones.

**Comment by warlordjones** [comment]
I'm looking at implementing a block like your second idea, gotta discuss with the team first. Beacon I'm not sure about.

**Comment by Rious** [comment]
Fantastic, cause i really love that texture for ominous builds, and Thaumcraft related stuff.

if I may add: would it be possible to make a "glass" kinda block, meaning that the moving ender textures are all around the block. with connected textures?

**Comment by Drullkus** [comment]
Beacons have been in my consideration for quite a while. Since we now have tterrag who seems experienced with NBT, it seems logical to put that on our roadmap. Possibly up-down orientations as well.

I'm not sure what you're talking

**Comment by Rious** [comment]
Yeah, i really hope beacons do get some love aswell :)

I might be bad at explaining, but what i wanted, was a block that looks alot like the void stone, but uses the particles like the waterstone and lava stone (found inside end chests / end portals) see link.
imgur.com/a/ioBVm

**Comment by CptSpaceToaster** [comment]
The check on line 76 may need to check against the upper limit, to avoid OOB exceptions

**Comment by warlordjones** [comment]
Also made redundant by #316
