### ISSUE TITLE
Project Red integration

### ISSUE THREAD

**Issue by JadeCreeper** [Chisel-2/Chisel-2#153]
Project Red integration should be added for basically one reason: The lamp blocks get boring.

It would be cool if Lamp blocks could be chiselable.

**Comment by Drullkus** [comment]
._." What do you mean they got boring

**Comment by warlordjones** [comment]
Hmm, forget lamps for a minute, Basalt integration would be cool. Possible in the future.

**Comment by BBoldt** [comment]
I could have swore basalt got added but idk where it went.

**Comment by warlordjones** [comment]
Redundant due to #316
