### ISSUE TITLE
CarveableHelper reworking

### ISSUE THREAD

**Issue by Drullkus** [Chisel-2/Chisel-2#178]
We should retool the CarveableVariation class so we can actually combine features (CTM randomization, assigning diff CTM for diff sides of block, etc)

So far we use switch cases with breaks at the end of each, which makes it nonflexable.

**Comment by Yulife** [comment]
@SoundLogic / @tterrag1098  will this break anything on Modtweaker's variation site? *flees*

**Comment by tterrag1098** [comment]
@Yulife unlikely.

@Drullkus I completely agree, it's a total mess and makes ICarvable all but useless.

**Comment by Drullkus** [comment]
Oops, I was actually talking about CartableHelper :)

https://github.com/TheCricket/Chisel-2/blob/dev/src/main/java/com/cricketcraft/chisel/carving/CarvableHelper.java

**Comment by Drullkus** [comment]
Poke @TheCricket

**Comment by TheCricket** [comment]
I get an email for everything that happens on the repo anyways...

**Comment by warlordjones** [comment]
Done.
