### ISSUE TITLE
Underground Biomes Constructs Integration

### ISSUE THREAD

**Issue by ChaoticTabris** [Chisel-2/Chisel-2#181]
It would be really nice to see Chisel options for the stones from Underground Biomes, it would be also be nice to have the stones from this mod be interchangeable with their versions on Chisel 2 (Basalt, Limestone and the 1.8 stones are the only ones that "conflict").

**Comment by PavelInt** [comment]
And twilightforest please.

**Comment by warlordjones** [comment]
Added to #316
