### ISSUE TITLE
Present Box Visual glitch

### ISSUE THREAD

**Issue by VictiniX888** [Chisel-2/Chisel-2#227]
If the Present Box is connected to another Present Box (Double Present Box?) and is chiseled, it won't change visually, however the colour changes in WAILA, and if broken, the colour is also changed.

Chisel version: 2.3.6.55807a5
Forge version: 1307

**Comment by tterrag1098** [comment]
Yeah this is because ICarvable blocks are not notified when their variation changes. It's a planned feature for the API in 2.4.

**Comment by warlordjones** [comment]
Seems to be fixed.
