### ISSUE TITLE
Crash when using marble

### ISSUE THREAD

**Issue by justjort** [Chisel-2/Chisel-2#230]
So, I was playing around with chisel version 2.3.5.1e7d12f, I placed a piece of marble in a diamond chisel, and my minecraft window closed leaving me with the following error report:
http://pastebin.com/P0WbDhVw
I noticed this issue happened on all versions that have the diamond chisel.
I am playing on multiplayer, but it appears to be a client side issue anyway

**Comment by warlordjones** [comment]
Cannot reproduce with chisel marble.

**Comment by warlordjones** [comment]
^
