### ISSUE TITLE
Feature request: Auto Chisel reversion upgrade?

### ISSUE THREAD

**Issue by jngeist** [Chisel-2/Chisel-2#271]
I love the Auto Chisel. It's fantastic for builds using large amounts of chisel blocks. When I'm doing builds that use lots of different Chisel variants, though, I find that I often end up with storage clogged up with small amounts of many different variants of the same block. At present, if I want to mass convert Chisel blocks back to their base blocks, I have to have one Auto Chisel set up for each type of block I'm using. That's certainly not impossible, but if you use the mod a lot, that can quickly become a lot of Auto Chisels all, essentially, doing the same job. 

It occurs to me that there's a simple solution that wouldn't require adding any blocks to the mod: a Reversion Upgrade for the Auto Chisel. This upgrade would block out (or just ignore) the Target Block slot, and instead convert any item pumped into the Auto Chisel to its un-Chiseled form. With this upgrade, I could throw Spruce Parquet, Huge Cobblestone Tiles, and Marble Panel into a chest, have them all run through the same Auto Chisel with a Reversion Upgrade, and have them converted to Spruce Wood Planks, Cobblestone, and Raw Marble, respectively. 

I suspect that this could be made even simpler to program by making this the default behavior for an Auto Chisel with no Target Block set. Then you wouldn't even need to add any items to the game (or upgrade slots to the Auto Chisel UI).

Thanks for listening!

**Comment by CptSpaceToaster** [comment]
DIfferent Suggestion:
Allow the auto chisel to accept any input variant, while still outputting the selected one.

Example: The input could be ANY cobblestone variant, output would be cob-french2.

I don't think chisel2 should force users into useless crafting to support this addition, but I could be very wrong here.  Does this sound safe?  Or am I stomping on other logic here?

**Comment by TheCricket** [comment]
It already does that, you can input any cobble variant and the target is all the same.

**Comment by tterrag1098** [comment]
@CptSpaceToaster Is that not...how it works? You only specify the target block, what you input can be any block in that carving group.

**Comment by CptSpaceToaster** [comment]
Then what exactly is the problem that the OP has?

**Comment by TheCricket** [comment]
working on this tomorrow

**Comment by TheCricket** [comment]
done
