### ISSUE TITLE
Forge Micro-block compatibility 

### ISSUE THREAD

**Issue by ShawnRHayes** [Chisel-2/Chisel-2#276]
title says it all , ending up with a bunch of untextured micro-blocks in the latest build

**Comment by CptSpaceToaster** [comment]
uhoh

**Comment by Drullkus** [comment]
Is it those damn blocks with multiple textures? (v4, v9, r4, etc)

**Comment by tterrag1098** [comment]
@ShawnRHayes Could you maybe provide screenshots? Examples? Something? I know for a fact that FMP still works, so we need some proof of the problem.

**Comment by ShawnRHayes** [comment]
http://gyazo.com/480d4f81bcb730b119c67d13bd213e29 http://gyazo.com/6de050d6749327e98034ed4e5925c93e 
http://gyazo.com/8fb6f6b07a2de79bb2cbe81ff2383982 

pic's of the issue running on forge 1307

**Comment by tterrag1098** [comment]
Those blocks have never worked with FMP because of their rendering. It's
not new behavior.

**Comment by CptSpaceToaster** [comment]
Did we do anything in 2.3.7 to 2.3.8 to expose this though?

**Comment by ShawnRHayes** [comment]
is there a way for micro-blocks to ignore those blocks as usable so they don't show up in NEI ?

**Comment by Drullkus** [comment]
@CptSpaceToaster Nope, it's been there since the dawn of time

**Comment by warlordjones** [comment]
We could create some kind of blacklist to prevent broken blocks from being added to FMP though

**Comment by MrGreenTea** [comment]
The vanilla torches can be placed in multipart blocks. Would it be possible to make this possible for the chisel variants too?

**Comment by tterrag1098** [comment]
@MrGreenTea like this? ;)

![](http://puu.sh/h3e4t.jpg)

**Comment by MrGreenTea** [comment]
Yes please! and like this :)
![2015-04-06_12 08 42](https://cloud.githubusercontent.com/assets/9407731/7003121/c95a6ab8-dc55-11e4-8b8b-7e74e6253821.png)

**Comment by warlordjones** [comment]
Torch FMP compat implemented a while ago
