### ISSUE TITLE
No valid textures tile .metalOre.0.desc

### ISSUE THREAD

**Issue by Maokuma** [Chisel-2/Chisel-2#284]
Client works fine but my private server crashes at startup with: http://pastebin.com/dTN3ZBcW (crash log)
Tested: Chisel2_DEV-2.3.9.89.jar
Using forge 1291 and McMyAdmin on ubuntu linux with java 1.8.0_40 and ca 3gb ram. (Test server)
/Thanks for looking into it devs

**Comment by tterrag1098** [comment]
We probably need to not be doing any texture stuff on the server, the old getResource calls worked (even though they were pointless) but now it fails.

**Comment by warlordjones** [comment]
Previously fixed.
