### ISSUE TITLE
Config option for concrete blocks

### ISSUE THREAD

**Issue by algul** [Chisel-2/Chisel-2#289]
Would it be possible to add config option to make concrete collision box as full block and not "soul sand" type of block. I love how the concrete blocks look, but this drop in makes them hard to use as floors.

**Comment by tterrag1098** [comment]
That's how concrete works, if you take that away, it doesn't make you
faster anymore.

**Comment by algul** [comment]
I would gladly sacrifice the speed. I have that speed boost disabled already.

**Comment by CptSpaceToaster** [comment]
So... you just want another block that looks like concrete...

**Comment by tterrag1098** [comment]
Having a config to disable the effects of concrete isn't that terrible an
idea.

**Comment by algul** [comment]
Yes @CptSpaceToaster that's exactly what I would love to have(with the connected textures on some of the concrete blocks). But coding new block to visually mimic concrete seem like unnecessary overkill. 
Looking at the code of BlockConcrete there is hardcoded value in the getCollisionBoundingBoxFromPool method. If I'm not mistaken that's the "drop in" value. Maybe just changing that value depending on config file would be enough.

**Comment by CptSpaceToaster** [comment]
I think we should just take the existing config, and make it also disable the change to the hitbox...

**Comment by tterrag1098** [comment]
Agreed
