### ISSUE TITLE
Granite hardness

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Chisel-2/Chisel-2#300]
Isn't granite, like, supposed to be harder than stone and cobblestone? 

I mean I get it, this mod is supposed to be about aesthetic. But it would be nice to have some FUNCTIONAL need for some of these blocks. Granite being one of them. Being harder than stone and cobblestone. Protecting better against...well...friggin creepers!

**Comment by TheCricket** [comment]
I wouldn't call this an issue

**Comment by tterrag1098** [comment]
Is it harder in 1.8? That is what we are basing it off of.

**Comment by TehNut** [comment]
From my memory, no, they are more or less the same.
