### ISSUE TITLE
Crash with rendering MarblePillarBlock

### ISSUE THREAD

**Issue by sheynandr** [Chisel-2/Chisel-2#301]
Hi. My minecraft will crashed when i'm loading Marble Block.
Crash-report see in my gist https://gist.github.com/sheynandr/f6f16ee6cee3b7b5a47c
P/S I don't know how reproduce this crash. This is random....

Versions: 
`Minecraft 1.7.10`
`Chisel2-v1.7.10-Dev 101 build`

**Comment by tterrag1098** [comment]
The crash report says you are on 100, not 101.

**Comment by sheynandr** [comment]
>The crash report says you are on 100, not 101.
Yes. This crash in build 100, but in build 101 also crash.

**Comment by sheynandr** [comment]
Okay. I will download build 102 and test them.

**Comment by sheynandr** [comment]
Crash with build 102.
Crash-report https://gist.github.com/sheynandr/775306804068ae095681

**Comment by tterrag1098** [comment]
That is a different issue and already fixed here: https://github.com/TheCricket/Chisel-2/commit/65693b868c099efeaa2b6eef81bacce679232ad2#diff-4f71961547e4010f95a88d7702a63322L81

**Comment by sheynandr** [comment]
Okay. I'm try to compile this tree and write them.

**Comment by CptSpaceToaster** [comment]
@sheynandr Or just wait till the next stable dev version compiles

**Comment by tterrag1098** [comment]
These changes aren't on the dev branch yet, so that won't work until this
is merged in
