### ISSUE TITLE
Register Diorite, Andesite and Granite in the OreDictionary

### ISSUE THREAD

**Issue by ganymedes01** [Chisel-2/Chisel-2#305]
Botania and Gany's Surface already do.

Vazkii and I agreed on the following names:

stoneGranite
stoneGranitePolished
and so on...

**Comment by tterrag1098** [comment]
@ganymedes01 Chisel typically registers all the subtypes to the same name, is having *Polished really necessary?

**Comment by ganymedes01** [comment]
Well, as long as the basic types are registered I think it should ve okay :3
