### ISSUE TITLE
Pillars render incorrectly

### ISSUE THREAD

**Issue by tterrag1098** [Chisel-2/Chisel-2#306]
Version: DEV-2.4.0.104

Problem code: https://github.com/Chisel-2/Chisel-2/blob/dev/src/main/java/com/cricketcraft/chisel/block/BlockCarvablePillar.java#L42-L47

**Comment by CptSpaceToaster** [comment]
Link is broken.

**Comment by tterrag1098** [comment]
Exactly. This code has basically been rewritten so, I assume it's fixed. If not, a new issue is needed.

**Comment by CptSpaceToaster** [comment]
:+1:
