### ISSUE TITLE
Build 104 - Crash on Server Startup (Only Server)

### ISSUE THREAD

**Issue by Zoryn4163** [Chisel-2/Chisel-2#309]
Crash-report: http://pastebin.com/PMYGE5v2
Forge log: http://pastebin.com/MsY3G0QG
Forge server log: https://drive.google.com/file/d/0B-_iReN21PiISDZGM1ljc0tncG8/view?usp=sharing (Exceeds max pastebin size)

Chisel Version: Chisel2_DEV-2.4.0.104.jar
I don't know how to find the Forge version, but I'm using the Direwolf20 1.2.1 FTB Modpack (The server of.) and have the file 'FTBServer-1.7.10-1291', so possibly forge 1291?

Note: I don't know what (if any) personal/useful information is recorded in those files.

The client runs just fine, and the server has the exact same setup to my knowledge.
If you'd like a client log I can provide that as well, but the client doesn't seem to crash so I don't think it'd be helpful.

Edit: Server runs fine on build 103 (Chisel2_DEV-2.4.0.103.jar) but crashes both client and server when a player attempts to chisel anything.

**Comment by Zoryn4163** [comment]
Hey, I saw "Fix #308 #309 Crashes on startup" in the Jenkins for Version 105 and get crashed on server start up only still.

Crash-report: http://pastebin.com/hkPxfdTw

**Comment by tterrag1098** [comment]
Alright, let's try again then :)

**Comment by Zoryn4163** [comment]
Still seems to be getting that same crash?
http://pastebin.com/xtvLJb8K

**Comment by tterrag1098** [comment]
Oh duh...my bad, one moment

**Comment by tterrag1098** [comment]
I tested it on my own server, and it worked fine. So let me know.

**Comment by Zoryn4163** [comment]
Nope :(
http://pastebin.com/ThsKH5Q1
Have to go for a while, might be another mod causing problems with it... oh well.

**Comment by Drullkus** [comment]
This is interesting

Caused by: java.lang.RuntimeException: Attempted to load class blm for invalid side SERVER
