### ISSUE TITLE
Diamond duping

### ISSUE THREAD

**Issue by mr10movie** [Chisel-2/Chisel-2#317]
So uh... is this intentional?
![](http://i.imgur.com/XTZy8bj.png)
Because this kinda feels like it shouldn't be intentional.

**Comment by TehNut** [comment]
Why would you ever post this publicly?

Also I cannot reproduce.

**Comment by mr10movie** [comment]
Because this means that this is a local issue (as I suspected). Nobody on the server I'm on knows about this issue but me and the owner, so we're fine.

Are there any ways that a mod could do this? It would help us find the culprit.

**Comment by tterrag1098** [comment]
I suspect someone is registering the diamond item to the diamond block
oredict. Could you please find out if that is true?

**Comment by mr10movie** [comment]
Nope, that doesn't seem to be the case:
[CHAT] Is in <ore:gemDiamond>
[CHAT] Is in <ore:diamond>

It IS GT doing this, I just confirmed, as removing it fixes this.

**Comment by Drullkus** [comment]
Which mod is it? We'll perform a witch hunt.

**Comment by mr10movie** [comment]
Greg, *obviously*.

**Comment by mr10movie** [comment]
It must be something other than the oredictionary though, as diamonds are registered as normal. Is there anything that could cause this that isn't oredictionary related?

**Comment by tterrag1098** [comment]
So with GT installed this happens? And not without GT?

**Comment by mr10movie** [comment]
Yeah, exactly. It definitely has nothing to do with oredict though as far as I can see. Diamonds are just registered as gemDiamond and diamond

**Comment by mr10movie** [comment]
I turned off diamond conversions in the config, which has the side effect of removing all the chisel diamond blocks apparently. It's the best temporary solution we have I think.

**Comment by mr10movie** [comment]
Update from Greg:

I checked everything on my Side and nothing does anything OreDict related with blockDiamond in my whole Modded Setup (except me adding my own Diamond Storage Block to the Game), and I do have Chisel installed and I do get that Bug too. It is not an OreDict Issue, it must be something else.

I would ask the Chisel Dev how his Mod decides what Stuff is a Diamond Block and what not. Because he is the only one who knows what his Mod does.

**Comment by tterrag1098** [comment]
I will install greg tech and try to determine why this happens,  later
today.

**Comment by TheCricket** [comment]
Diamond Block: http://prntscr.com/7av0po
Diamond: http://prntscr.com/7av0xt

**Comment by Andrey96** [comment]
Same thing (screenshot of NEI recipe) http://i.snag.gy/oGXG0.jpg

**Comment by Andrey96** [comment]
Temporary fast-made fix from me https://gist.github.com/Andrey96/4f35da40909ed4e60b9d
Adds to config string list 'restrictedItems' in 'general' category with item ids (in our case it's minecraft:diamond and IC2:itemPartIndustrialDiamond)

**Comment by Drullkus** [comment]
We already made the fix.

**Comment by Andrey96** [comment]
Okay, but I still have this issue with the mod built yesterday from this repo. So, I made the fix too.

**Comment by Drullkus** [comment]
If you want to submit the code to chisel, make a PR :P

**Comment by CptSpaceToaster** [comment]
@Andrey96 Did you build off `master`, or `dev`?  The dev branch is holding the fix...

**Comment by Andrey96** [comment]
Oh... I built master branch
