### ISSUE TITLE
X-ray Block

### ISSUE THREAD

**Issue by MySt1k** [Chisel-2/Chisel-2#318]
![2015-05-16_15 05 18](https://cloud.githubusercontent.com/assets/5097581/7665535/2062ccfa-fbdd-11e4-97ba-9b51865f4a3f.png)
![2015-05-16_15 05 25](https://cloud.githubusercontent.com/assets/5097581/7665534/20617d6e-fbdd-11e4-9aa0-d7ce06bb6467.png)

forge 1.7.10-10.13.3.1388
chisel - last version

Block id - 599

**Comment by tterrag1098** [comment]
"Latest version" is not helpful, please post the exact version you are
using. Also, the name of the block, the numeric ID is useless as it is not
constant.

**Comment by warlordjones** [comment]
It appears to be one of the lab blocks. Investigating.

**Comment by TheJulianJES** [comment]
Update OptiFine

**Comment by warlordjones** [comment]
Cannot reproduce.
