### ISSUE TITLE
Bookshelves CTM is backwards

### ISSUE THREAD

**Issue by ScottKillen** [Chisel-2/Chisel-2#320]
Place two bookshelves next to each other...the textures change to the CTM versions, but the border disapparates from the wrong side...  (See below)

![2015-05-19_18 24 44](https://cloud.githubusercontent.com/assets/1509989/7715364/cdf7acea-fe54-11e4-81a0-e6cc235c3c1c.png)

**Comment by Drullkus** [comment]
Looks like a problem with CTMV

**Comment by tterrag1098** [comment]
Yep, backwards indeed :)
