### ISSUE TITLE
Request: Implement EE3 Compatibility

### ISSUE THREAD

**Issue by WolfAmaril** [Chisel-2/Chisel-2#321]
Chisel seems to be breaking some basic EE3 functionality pahimar/Equivalent-Exchange-3#887 and given that the EE3 API is not out I was wondering if you'd consider adding EE3 compatibility.

**Comment by Drullkus** [comment]
One week late there, bud. We already added it like a week ago :p

**Comment by tterrag1098** [comment]
Except it was done wrong...

**Comment by WolfAmaril** [comment]
And doesn't seem to be in the git repo...
Or any of the downloads available on curseforge...

**Comment by tterrag1098** [comment]
It's on the dev branch and in dev builds.

**Comment by WolfAmaril** [comment]
Ah, fair point.

**Comment by warlordjones** [comment]
I think this is codecomplete?
