### ISSUE TITLE
[feature request] make the chisel repairable

### ISSUE THREAD

**Issue by Ephys** [Chisel-2/Chisel-2#323]
It would be nice if one could repair the chisel in an anvil using iron/diamonds.

It would also allow the timeless ivy to work on the chisel

**Comment by Drullkus** [comment]
It's stupidly cheap, just one iron or one diamond. Is there a point?

**Comment by Ephys** [comment]
Everything looks better without a durability bar ?

I know it's cheap, I've been using the same chisel for months and it has lost like 2% of its durability. But it feels cleaner fully repaired and is the only item left in my inventory that looks damaged :/

(yes this is a stupid reason)

**Comment by Drullkus** [comment]
Craft a new one.

**Comment by tterrag1098** [comment]
If this is really easy to do (I think it will be) then I'll do it. If I
come across any major roadblocks this won't be a priority.
