### ISSUE TITLE
Forge 1420 Incompatibility?

### ISSUE THREAD

**Issue by Xiaminou** [Chisel-2/Chisel-2#326]
I tried updating to my modpack to forge 1420 and this is what I got on my server (client is fine thought): http://pastebin.com/JXRfukaB

of course I tried to disable the abyssal blocks but this is just one of many not working: http://pastebin.com/1Yu73szU

**Comment by tterrag1098** [comment]
Did you update Railcraft? @CovertJaguar did something change again?

**Comment by Xiaminou** [comment]
No I did not update Railcraft recently, and it rolled back to forge 1403 and it works. Might it be something with kcauldron?

**Comment by tterrag1098** [comment]
Yes please try to reproduce without cauldron

**Comment by Xiaminou** [comment]
Alright, I'll give it a shot later

**Comment by TheCricket** [comment]
no reply assuming fixed
