### ISSUE TITLE
Do not run the server

### ISSUE THREAD

**Issue by MySt1k** [Chisel-2/Chisel-2#327]
Chisel2_DEV-2.4.0.122
http://pastebin.com/0aE8YaiB
http://pastebin.com/RXt5QvME

**Comment by TheCricket** [comment]
Testing right now

**Comment by TheCricket** [comment]
finishing testing now

**Comment by tterrag1098** [comment]
This log is confusing. Are you running from source? If so why is the file
name "chisel-1.jar"???

**Comment by TheCricket** [comment]
I fixed it

**Comment by MySt1k** [comment]
To keep fashion in alphabetical order. Maud clean

**Comment by TheCricket** [comment]
https://github.com/Chisel-2/Chisel-2/commit/f62b444509be05aab295e168d7d9037d38b8211e
