### ISSUE TITLE
TiCon compatibility

### ISSUE THREAD

**Issue by karakufire** [Chisel-2/Chisel-2#328]
Tinker's construct has some chiselable blocks, I want chisel-2 support them.

And the mod has same name tool. I think it good as either chisel feature overwrite other one.

**Comment by tterrag1098** [comment]
@TheCricket Another thing for ChiselCompat if you do it

**Comment by Zsashas** [comment]
Um...isn't this already possible? I'm assuming you're talking about the different variants of bricks and such, like Fancy Stone Bricks. Pretty sure Chisel can already get those.

**Comment by TheCricket** [comment]
it is but were not doing it in this mod

**Comment by karakufire** [comment]
After this work, should compatibillity requests/suggestions post to chiselcompat's issue?

**Comment by TheCricket** [comment]
yes and were not working on it in chisel

**Comment by Zsashas** [comment]
"it is but were not doing it in this mod"
I'm a little confused what you mean by this. Chisel is directly capable of chiselling blocks into variants added by other mods. Is this NOT a native Chisel function? If not, what does do it?

**Comment by TheCricket** [comment]
ChiselCompat is a mod for all mod compatibility to happen

**Comment by Drullkus** [comment]
I thought I added this bloody support. Where'd it go?

**Comment by TheCricket** [comment]
To chisel compat

**Comment by Drullkus** [comment]
Did we already move it away from chisel? That'll nuke all of the modded blocks people have in their worlds.

**Comment by TheCricket** [comment]
It remaps them, and we can setup to auto download chisel compat

**Comment by Drullkus** [comment]
Remapping is irrelevant if Chisel is installed but ChiselCompat isn't.
