### ISSUE TITLE
Jenkins server has been stuck for a few days now...

### ISSUE THREAD

**Issue by ate0ate** [Chisel-2/Chisel-2#329]
The Jenkins server has been attempting to build dev build 123 for 4 days and 15 hours now. I could be mistaken, but I think that it may be frozen:P Build 124 is obviously stuck pending as well. Figured I'd mention it here since I haven't seen it brought up anywhere yet. Thanks!

**Comment by tterrag1098** [comment]
Thanks, I gave it a kick. IRC notifier gets stuck sometimes. Speaking of which, in the future it would be better to bring something like this up on IRC.
