### ISSUE TITLE
Crash to desktop when you try to chisel stone. 

### ISSUE THREAD

**Issue by demethan** [Chisel-2/Chisel-2#331]
[Crash log](http://pastebin.com/Gdz2grRV)
[Mods in that pack](https://www.atlauncher.com/pack/liteLunch)

When inserting stone into the chisel, crash to console. Not sure why. I have the same version on a different pack and it works fine.

**Comment by spamenigma** [comment]
Same problem and error here, it mentions "at codechicken.nei" which I've just updated to NotEnoughItems-1.7.10-1.0.5.111-universal
CodeChickenCore-1.7.10-1.0.7.46-universal

Hope this helps find a fix.

**Comment by tterrag1098** [comment]
NEI has nothing to do with this.

**Comment by svenwilke** [comment]
I have the same problem on my server. It started happening after I updated ProjectRed to the newest version (4.6.1.80 -> 4.7.0pre1.84)

**Comment by ePaulista** [comment]
Same problem here

**Comment by spamenigma** [comment]
I've now seen it crash with stone > stone brick in normal crafting (not chisel2). Also using the updated ProjectRed 4.7.0pre1.84 so tested without that and its all working.

**Comment by tterrag1098** [comment]
This is a ProjRed issue, bring it to them.

**Comment by spamenigma** [comment]
Thats my point! try not being so rude!
