### ISSUE TITLE
Config option to disable tooltip of generated blocks

### ISSUE THREAD

**Issue by Adaptivity** [Chisel-2/Chisel-2#339]
Is it possible to add a config option to disable "Generates in your world" tooltip which is appears on Diorite/Andesite/Granite?

**Comment by TheCricket** [comment]
What would you like it to be instead? just nothing?

**Comment by Adaptivity** [comment]
Yes. Just nothing.

**Comment by TheCricket** [comment]
alright

**Comment by TheCricket** [comment]
You ask for something strange, I give you something strange :palm_tree: :8ball: :dancer:

**Comment by Adaptivity** [comment]
Thanks!

**Comment by TheCricket** [comment]
Best config name ever

**Comment by Adaptivity** [comment]
Hmm, imTooGooForBlockDescriptions in Configurations.java. Goo? Block? Shouldn't this be imTooGoodForDescriptions? Just to be sure

**Comment by TheCricket** [comment]
yeah... I can spell

**Comment by TheCricket** [comment]
On the ball lately with fixing typos

**Comment by Drullkus** [comment]
10/10 would disable

**Comment by warlordjones** [comment]
See #103 for an explanation

**Comment by tterrag1098** [comment]
Dude....stop reopening issues.
