### ISSUE TITLE
Crash placing creative spawned hex plating? (dev build 132)

### ISSUE THREAD

**Issue by ate0ate** [Chisel-2/Chisel-2#341]
I attempted to place a cyan hex plate block in creative and this, ridiculously lengthy, crash followed...
https://www.dropbox.com/s/fttg9pgpjabymiq/crash-2015-06-22_23.54.34-client.txt?dl=0

**Comment by Choonster** [comment]
Are you sure that's the right crash report? Judging by the stack trace, it seems that crash happened in postInit rather than during gameplay.

To find the source of that crash, we'd need to see your FML log since HEE has apparently written the offending recipes to it.

**Comment by ate0ate** [comment]
I initially did post the wrong crash report but corrected it shortly after. Check the link again and it should be the right one. No mention of recipes or HEE anywhere. I will post the fml logs as soon as possible. Sorry about that.

**Comment by TheCricket** [comment]
I know what I did wrong :P
