### ISSUE TITLE
Server Crashes, i suspect Chisel.

### ISSUE THREAD

**Issue by iGoodie** [Chisel-2/Chisel-2#344]
On our server which has Chisel 2 - version2.3.10.37 installed, the server crashes time to time.
I suspect Chisel for this, because right before the server closes console prints these out:
![error](https://cloud.githubusercontent.com/assets/8591785/8331676/391d0de0-1a92-11e5-9033-7fee68f17cfe.png)

**Comment by Choonster** [comment]
Those warnings have nothing to do with the crash. They're always displayed.

The crash happened earlier in the log, we'd need to see the crash report to help you any further.

**Comment by TheCricket** [comment]
Unable to lookup is not a problem, do not treat it as such
