### ISSUE TITLE
Connected textures no longer lining up with 2.4.0.38

### ISSUE THREAD

**Issue by utoc** [Chisel-2/Chisel-2#351]
Hello!

I've updated to Chisel2 v2.4.0.38 and found that connected textures with EnderIO's painted conduit no longer line up with Chisel blocks and connected textures

Previous version 2.3.10.37 had the following rendering: https://i.imgur.com/8DOkCHx.png

Current version 2.4.0.38 has the following rendering: https://i.imgur.com/BeZYsNb.png

What the conduit looks like underneath:  https://i.imgur.com/Tcjsn2j.png

We're running EnderIO 2.2.8.381; it was not updated in this past release, only Chisel.  FML 1448.  Please let me know if I can assist and debug in any way.

EDIT: Links were backwards :)

**Comment by TehNut** [comment]
Did you mix up your images? Or am I reading wrong?

Because from what I'm seeing, the newer version is working correctly.

**Comment by utoc** [comment]
My mistake; I've corrected the bug report.

**Comment by TheCricket** [comment]
this is an enderio issue its not our problem

**Comment by tterrag1098** [comment]
What? This is our blocks not connecting to facades. How is it not on our
side?

**Comment by TheCricket** [comment]
Because they aren't our facades

**Comment by tterrag1098** [comment]
And? They implement OUR API

**Comment by TheCricket** [comment]
Fine

**Comment by tterrag1098** [comment]
Fixed via https://github.com/Chisel-2/CTMLib/commit/a2fbb4b1476ff9bd3b9851d24e8e274d00ff3277

**Comment by utoc** [comment]
This is working correctly in 2.4.1.40.  Thank you @tterrag1098
