### ISSUE TITLE
[2.4.0] Broken textures

### ISSUE THREAD

**Issue by JasonMcRay** [Chisel-2/Chisel-2#354]
I am having graphical glitch issue with some of chisel blocks. When they are placed in the world the blocks are getting transparent.
![2015-07-01_21 14 15](https://cloud.githubusercontent.com/assets/4236895/8462766/5ecd0262-2036-11e5-97f9-0242fb9460e4.png)

Its happening only with Optifine, but it did not happend in 2.3.10 version of Chisel

If i should go and shout at Optifine, just say, close and forget :)

**Comment by TheCricket** [comment]
Yes go yell at optifine
