### ISSUE TITLE
Chisel 2 item problem

### ISSUE THREAD

**Issue by emremre** [Chisel-2/Chisel-2#356]
Hi!

I have a very big problem. I do not understand why this is happening.

http://i.imgur.com/1fYussx.png?1

I enjoyed playing this game when I saw it breaking.

Thanks...

**Comment by TheCricket** [comment]
You are using a texture pack...

**Comment by emremre** [comment]
Yes. But the problem is not in it.
Because I tried.
Game version: 1.7.10
Forge version. 10.13.2.1291
Chisel 2 verison: 2.3.10.37

**Comment by TheCricket** [comment]
Its not the version

**Comment by emremre** [comment]
What should I do?

**Comment by TheCricket** [comment]
Its not our fault.

**Comment by tterrag1098** [comment]
You are also quite outdated. Try with 2.4.1
