### ISSUE TITLE
Hardcoded message spotted

### ISSUE THREAD

**Issue by Adaptivity** [Chisel-2/Chisel-2#358]
https://github.com/Chisel-2/Chisel-2/blob/ad012c51800a6527b12ee9ca2dd9dc67acfd8b42/src/main/java/com/cricketcraft/chisel/Chisel.java#L210 I should translate this. No doubts. Use *new ChatComponentTranslation* here.

**Comment by tterrag1098** [comment]
The message is going away next version. It was just a temp thing. No worries.

**Comment by Adaptivity** [comment]
=(
