### ISSUE TITLE
Energized voidstone blocks are not placing correct block.

### ISSUE THREAD

**Issue by itanshi** [Chisel-2/Chisel-2#360]
Picture showing results.

![results](http://i.imgur.com/dkciLrA.png)

Using version 2.4.1.40

**Comment by TheCricket** [comment]
known

**Comment by eslachance** [comment]
So, my question here is... it's *known*, but will it be *fixed*? There's no indication on a resolution, or a version, or a build number...

**Comment by minecreatr** [comment]
@eslachance It is fixed in the CT Chisel

**Comment by eslachance** [comment]
I'm sorry to have to ask but... what's CT Chisel?

**Comment by minecreatr** [comment]
@eslachance An new branch of chisel, its a long story but github is here https://github.com/Chisel-Team/Chisel

**Comment by eslachance** [comment]
Ah I see. I'm... not one to build from source, is there a build somewhere? Sorry if I'm being a hassle.

**Comment by eslachance** [comment]
Oh nevermind. there's a link. Derp.

**Comment by tterrag1098** [comment]
Releases are here http://www.curse.com/mc-mods/Minecraft/235279-chisel

**Comment by Spazzze** [comment]
Link by tterrag1098 for Chisel, but this topic related to Chisel 2.
Atm latest release of Chisel 2 - 2.5.1, I have it and this problem still persist, Energized voidstone blocks are not placing correct block
What am I doing wrong? 
![2015-11-18_10 01 35](https://cloud.githubusercontent.com/assets/8989548/11233835/0279fdb6-8dd3-11e5-8cc4-ddc1382d7ca5.png)
