### ISSUE TITLE
Client crash when updating

### ISSUE THREAD

**Issue by yepidoodles** [Chisel-2/Chisel-2#361]
When updating from version 2.3.10 to any of the new versions, I get this client crash before the modpack even loads to the main screen.

https://www.dropbox.com/s/4an47p2b6j0ae3t/crash-2015-07-05_13.07.05-client.txt?dl=0

Hope you can help

Alice (yepidoodles)
DragonTechMC

**Comment by Choonster** [comment]
You're missing a required library. See #348.

**Comment by yepidoodles** [comment]
What library am I missing and how do I  get it?

**Comment by Choonster** [comment]
You have an older version of Apache commons-lang installed. Updating to Forge 10.13.3.1403 or newer should install the proper version.
