### ISSUE TITLE
Crash on Startup (NoClassDefFoundError)

### ISSUE THREAD

**Issue by TheUnlocked** [Chisel-2/Chisel-2#362]
Crash report: http://pastebin.com/ixy2p513

When I start up a modpack I'm making with chisel 2, it crashes on startup at the initialization stage. When I reverted to a previous version of the mod that worked in my pack, it crashed with the same error, making me think it's a compatibility error with an update of a mod I also updated. It's also possible that there was some sort of maven/java update that broke it due to the nature of the error, however I find this very unlikely.

I hope this helps. For now, I'll just use my pack without chisel. However, it would be nice to have this fixed. If you need any more information or help, I'd be happy to help!

-Unlocked

**Comment by tterrag1098** [comment]
#361 #348
