### ISSUE TITLE
Incompatibility between Opis (MapWriter) and Chisel 2

### ISSUE THREAD

**Issue by TheReturningVoid** [Chisel-2/Chisel-2#368]
Hello,

I'm currently working on a modpack containing your mod (Chisel 2) and Opis. Opis comes bundled with MapWriter. The problem is that MapWriter seems to trip up on getting colours from the blocks in this mod. The game will launch fine, however loading a world or joining a server causes this crash.

Crash log: http://pastebin.com/VvxJRARc

Forge version: 10.13.4.1481

Using Chisel 2 2.4.1.40, MobiusCore 1.2.5 and Opis 1.2.5.

Sorry if I should be reporting to ProfMobius here, but it does seem to be in issue with your mod.

Thanks in advance!
--TheReturinigVoid

**Comment by TheCricket** [comment]
I don't see how this is our issue it doesn't notice us anywhere

**Comment by TheReturningVoid** [comment]
Removing the Chisel mod stops the crashing.

**Comment by tterrag1098** [comment]
Regardless, something Mapwriter is doing is causing this. Chisel-2 must just be exposing it. The crash is not in our code.
