### ISSUE TITLE
FR: Relative texturing for Block "Arcane Stone Block: Fine Thaumaturge's Emblem"

### ISSUE THREAD

**Issue by netzgeist** [Chisel-2/Chisel-2#369]
Heres how "Arcane Stone Block: Braainz" does it:
http://i.imgur.com/H2fUrLc.png

Here's how Arcane Stone Block: Fine Thaumaturge's Emblem" fits in the same blockspace:
http://i.imgur.com/gFTmzUv.png

So I cant really use this awesome texture because its pure luck if it will fit the targeted blockspace. May you change its behavior to be placed more freely in the world?

**Comment by tterrag1098** [comment]
Same as #365 and unfortunately it can't really be fixed.
