### ISSUE TITLE
Hex Plating (non-black) do not retain colour when used to create BC facades

### ISSUE THREAD

**Issue by Novocastrian** [Chisel-2/Chisel-2#370]
I made the hex plating blocks and coloured them light blue with the Chisel, but when you throw those blocks into the assembly table, they render as black, despite the tooltip noting otherwise. 

Tooltip to indicate that the facade says that they are light blue: http://puu.sh/iW7rL/0426402dda.jpg
Block pre-facade with it's facade : http://puu.sh/iW7xO/55be82bb01.jpg

Using Chisel 2 version. 2.4.140 (latest according to Curse).

**Comment by TheCricket** [comment]
Thats not on our side, its functioning how they intended it, its getting the IIcon which is the overlay its a multi pass render on our side and they arent doing it

**Comment by tterrag1098** [comment]
Indeed, there is nothing we can do about this, Buildcraft can attempt to support our rendering if they so choose, but it is out of our hands.
