### ISSUE TITLE
Block texture bug

### ISSUE THREAD

**Issue by gabor6505** [Chisel-2/Chisel-2#374]
Some Chisel blocks don't have any texture in NEI, and if I place those down it goes to transparent, and then sometimes if I move, place blocks or if I do something, it fixes itself. I noticed this issue in my little Secret Base, but then I tested it in a New World too, but the same issue. I think the blocks that have transparent textures in NEI are the same in any world, any time.

Screenshots:

At Secret Base (older world):
![2015-07-13_10 57 57](https://cloud.githubusercontent.com/assets/12859334/8669247/2f2dc4e2-2a13-11e5-8644-f9092f2f1573.png)

In a New World:
![2015-07-14_10 31 49](https://cloud.githubusercontent.com/assets/12859334/8669303/adf047c8-2a13-11e5-9406-53678bb7b3b2.png)
![2015-07-14_10 31 57](https://cloud.githubusercontent.com/assets/12859334/8669304/b3070080-2a13-11e5-81f4-f713a5737483.png)
![2015-07-14_10 32 11](https://cloud.githubusercontent.com/assets/12859334/8669306/b74d2fb6-2a13-11e5-8617-ea7d55707123.png)

If you need modlist, or logs, or anything like that, tell me. Thanks for the help!

**Comment by tterrag1098** [comment]
Optifine?

**Comment by gabor6505** [comment]
Ohh I forgot about that, I have OptiFine, I will check it without it.

**Comment by gabor6505** [comment]
So I checked it without Optifine and the issue is went away. I tried to downgrade Optifine, because I remember that it worked before I updated some of the mods in my pack, including Optifine, because the new version now includes the fancy forge loading screen and i wanted that, but the issue still occurs if I downgrade 1 version. So maybe some of the newly added mods or updated mods can cause the issue too. I know mods don't really support Optifine, but is there any solution for this ?

**Comment by TheCricket** [comment]
Um... take optifine out and never use it again. If you "need optifine in order to play a pack" the pack is too big

**Comment by tterrag1098** [comment]
We cannot reasonably support issues that only arise with Optifine. Optifine makes too many changes to the game, most of which are massive hacks and cause lots of issues.

**Comment by gabor6505** [comment]
I found the solution for this (if anyone needs it), I didn't know where to put this, but if you disable Multi-Core chunk rendering (set it to Smooth or Default), and restart your client, than every Chisel block works again. :smile:
