### ISSUE TITLE
middle-clicking a chiseled bookshelf in creative retrieves a missing-texture-block

### ISSUE THREAD

**Issue by usafphoenix** [Chisel-2/Chisel-2#375]
middle-clicking a chiseld bookshelf  results in pink-block/black-block chessboard pattern as a texture in hotbar and when placed back down. (Chisel mod not correctly reading metadata to assign proper texture when middle clicking certain bookcases. (note that most of the other blocks work fine when middle clicked.)

but when trying to middle-click a chiseled bookcase, the four cardinal faces are checkerboard-patterns, while the top and bottom are the correct texture: oak. 

chisel version: 2.4.1.40

**Comment by TheCricket** [comment]
What version of chisel

**Comment by usafphoenix** [comment]
chisel version: 2.4.1.40

**Comment by TheCricket** [comment]
I thought we fixed that... screenshots please?

**Comment by usafphoenix** [comment]
![2015-07-22_20 15 16](https://cloud.githubusercontent.com/assets/10443617/8841020/76fd0fde-30ae-11e5-97a2-719c6544ea30.png)

**Comment by usafphoenix** [comment]
also tried forcing a light update and a block update, just to check.

**Comment by TheCricket** [comment]
Those wouldn't have an effect whatsover
