### ISSUE TITLE
Certain textures fail to load/display properly when using multi-threaded features in Optifine

### ISSUE THREAD

**Issue by gabor6505** [Chisel-2/Chisel-2#376]
I know, I know multi-threading can only be enabled in Minecraft by OptiFine right now, but I made pictures and collections, what is working, what is not. If you don't need it, ignore it, but we discussed, why not put it here if I already made it.

(Discussion / I came from here: [Reddit](https://www.reddit.com/r/feedthebeast/comments/3dud3d))

This is the Imgur album shows the not-working / glitching blocks: [Imgur Album](http://imgur.com/a/Inc03)

*I listed the glitching blocks in the description of every picture (at the bottom of the picture). I rotated my screenshots to follow the list I wrote. I know it is not necessary what I did, but I love to create collections, especially when I can create those in a little bit of a logical order. :D*

**Comment by CptSpaceToaster** [comment]
https://github.com/Chisel-2/Chisel-2/issues/374

**Comment by gabor6505** [comment]
I know. If you don't need it, just don't use it. But if Vanilla MC gets multi-threading compatible, than I think this issue will arrise without OptiFine too. But at least, you replied :smile:

**Comment by CptSpaceToaster** [comment]
If Chisel has an issue with vanilla, than it's an issue with Chisel.  We'll be more than happy to look into the problem.  Our goal as devs is to make sure that Chisel is Bug Free.

If Optifine changes something, and breaks Chisel, **then there is very little we can actually do**, short of wasting our time trying to work around issues that Optifine makes for us.  Feel free to report Optifine Specific issues to the devs of Optifine.

**Comment by TheCricket** [comment]
I have said this many a time. I absolutely hate that optifine exists. It is made for people with "slow computers" who "can't run packs without it". If you can't run the pack, you can't run the pack. remove some mods that you aren't going to play with. Find a smaller pack that also suits your playstyle. There are so many out there that there isn't an excuse. Minecraft itself is not multi-threaded. It was not made for this and it was certainly not intended for this. *deep breath* Ok rant over.

![TLDR](https://s-media-cache-ak0.pinimg.com/originals/1d/99/d7/1d99d7f286fec6bac7394be6c44d734a.jpg) 
I hate optifine and don't think it should exist

**Comment by TheCricket** [comment]
Thank you to @CptSpaceToaster for the beautiful image

**Comment by CptSpaceToaster** [comment]
With pleasure

**Comment by gabor6505** [comment]
Okay, no problem. But the main info is there for people uses OptiFine, that if they don't use Multi-Core Chunk Loading, or they don't use OptiFine Ultra, than this issue will not happen. I know this problem is not on your side, I will report it to OptiFine. But OptiFine helps optimizing everyone's FPS and performance. And I have a decent, very powerful computer, but if I use 185 mods in my modpack, I get like 30-40 FPS in just a fresh world. With OptiFine I get like 100... I mean I know you won't be able to fix that, and I don't said anything rude. That is just my opinion, that many people uses OptiFine, and like with the most powerful computer in the world (which probably like no one has right now), a 200-250 mod modpack will still lag without OptiFine, even worse if someone has a Giant base. And my opinion is that most of this optimization should be in Vanilla Minecraft, and I think Minecraft should officially support mods. (And I think a lot of other stuff as well, like why Bukkit, Cauldron and Spigot became like unavailable, but that not belongs here.)

**Comment by TheCricket** [comment]
A 200 - 250 mod modpack should lag, nobody should be running that much
