### ISSUE TITLE
Question about world gen

### ISSUE THREAD

**Issue by lightning02** [Chisel-2/Chisel-2#378]
this mod when added overwrites the existing chunk even in the presence of other mod or that the world needs to be recreated from scratch?

Your mod regens old chunks with its materials and stuffs?

**Comment by TheCricket** [comment]
I'm sorry?

**Comment by TehNut** [comment]
@TheCricket I think he's asking if Chisel has retrogen for all the worldgen materials.

**Comment by TheCricket** [comment]
I don't believe it retrogens but you shouldn't put this on the issue tracker its not the right place

**Comment by tterrag1098** [comment]
The answer is no @ReneMuetti, to be clear

**Comment by ReneMuetti** [comment]
What have I to do with it?
I asked no such question ....
* ask in it looks *

**Comment by tterrag1098** [comment]
Whoops, wrong tag, I meant @lightning02 

Don't ask how I mixed that up

**Comment by TheCricket** [comment]
GG

**Comment by alexbegt** [comment]
I blame @TheCricket.
