### ISSUE TITLE
Blocks not displaying correctly

### ISSUE THREAD

**Issue by crazymanofnwn** [Chisel-2/Chisel-2#384]
![2015-08-01_08 58 26](https://cloud.githubusercontent.com/assets/13600131/9021928/4af7da56-382c-11e5-9ccd-5daf2a012d2f.png)
![2015-07-31_23 29 33](https://cloud.githubusercontent.com/assets/13600131/9021929/4afd4734-382c-11e5-8359-54c9f14e59c9.png)

I've tried many ways to fix this but cannot seem to fix it.  
I am NOT running optifine.
I've tried forge versions from  1456 to the latest version and it still causes the same issue
Reinstalled nvidia GTX drivers. 

it looks as if the textures are inverted or something similar.  also the basic textures for a lot of the wood and stuff dont work either. 

I had Shaders mod in there. but I took it out thinking it was the issue. same thing.

**Comment by TheCricket** [comment]
if its a different texture none of that stuff was necessary. its obviously our issue

**Comment by tterrag1098** [comment]
What exactly is wrong in that second picture?

**Comment by tterrag1098** [comment]
And what version are you using? Can you detail the problem a bit more? 2 random screenshots doesn't really describe it.

**Comment by Blatts12** [comment]
Are You using Java 8?

**Comment by Drullkus** [comment]
The second pic has no lighting. I need lighting to understand :<

**Comment by Kolatra** [comment]
If you look at waila in the second picture, the texture with that and the one that is in the world are both different.

**Comment by Drullkus** [comment]
Still wanting light :(

**Comment by TheCricket** [comment]
![Is this bright enough?(http://prntscr.com/80e2f1)
Kinda like this lighting?

**Comment by Drullkus** [comment]
cricket pls

**Comment by crazymanofnwn** [comment]
Sorry everyone. The bugs are basically missing and inverted textures.  I was using the  2.4.1 version but didnt work. so I even tried the beta 2.5 and that worked but doesn't load on kCauldron. so went down to version Chisel 2.0.0.3-1 Universal and this one works.   but basically what was going on in the pics was the fans in the pics are missing in the technical blocks and wood textures are missing in the 1'st pic. 

I'm fine with using the older version Chisel 2.0.0.3-1 Universal.  it seems to work.

**Comment by TheCricket** [comment]
Nobody should be using 2.0's

**Comment by TheCricket** [comment]
Missing and inverted textures are something that we can work with overall, that's something with our problem and our problem only. We just need good screenshots or a list of the blocks so we can look at them on our end. Just so everyone knows in the future.

**Comment by TheCricket** [comment]
Everything checks out on my end
