### ISSUE TITLE
Crash in server start

### ISSUE THREAD

**Issue by Bogdan-G** [Chisel-2/Chisel-2#385]
Hello. Server: Cauldron 1.7.10-1492.150, 
Chisel2_DEV-2.5.0.154, crash-reports:
https://gist.github.com/Bogdan-G/e0432d76c11724e36292 | https://gist.github.com/Bogdan-G/3e38be2802d371833317
Chisel2_DEV-2.5.0.151: normal start.

Client MC 1.7.10, Forge 1492, both versions normal start.

**Comment by Choonster** [comment]
I believe the issue here is that `SubmapManagerRCTM` is missing `@SideOnly` annotations for the `createRenderContext` and `registerIcons` methods, so it's trying to load client-only classes on the server.

**Comment by TheCricket** [comment]
Yep he always does that
