### ISSUE TITLE
Minecraft crashes right after loading is done

### ISSUE THREAD

**Issue by bigyihsuan** [Chisel-2/Chisel-2#387]
Crash report: [Pastebin](http://pastebin.com/hJ9NXiTz)

Info:
* Forge 10.13.4.1448 for Minecraft 1.7.10
* Mods: [Picture](http://i.imgur.com/zep6Z93.png)
* Using Chisel2, version 2.4.1.40

**Comment by bigyihsuan** [comment]
I have a felling it's because EE3 doesn't have EMC values for a bunch of mod items currently.
I say this because of this line:

    cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/pahimar/ee3/api/exchange/EnergyValueRegistryProxy

**Comment by CptSpaceToaster** [comment]
If you remove EE3... does Minecraft load correctly?

**Comment by tterrag1098** [comment]
Same as #350

**Comment by bigyihsuan** [comment]
Yup, it works correctly.
