### ISSUE TITLE
EE3 compatibility crash/outdated.

### ISSUE THREAD

**Issue by StevenTheEVILZ** [Chisel-2/Chisel-2#388]
When i started the game, the game crashed, and after a while of looking, I've found that the issue is in the Compatibility class. There is no longer a exchange folder in the EE3 api folder. The EnergyValueRegistryProxy class is now just in the api folder, but this mod still does import com.pahimar.ee3.api.exchange.EnergyValueRegistryProxy, which no longer exists. Now it's com.pahimar.ee3.api.EnergyValueRegistryProxy for the recommended EE3 for 1.7.10. Can you please fix this. Thanks!

**Comment by TheCricket** [comment]
done

**Comment by StevenTheEVILZ** [comment]
thanks!

**Comment by StevenTheEVILZ** [comment]
i checked the source for EE3 on github and it has the exchange folder, but the downloadable compiled versions don't. Weird.

**Comment by Parker8283** [comment]
Uhh...no...the most recent builds of EE3 use the exchange folder.

**Comment by TheCricket** [comment]
So I will revert the change...

**Comment by StevenTheEVILZ** [comment]
Sorry! I was using the recommended version. I'll be more careful next time.
