### ISSUE TITLE
Server / Client Crash when trying to feed a diamond chisel into the Auto Chisel with Ender IO

### ISSUE THREAD

**Issue by Drethic** [Chisel-2/Chisel-2#392]
I tried to pull a diamond chisel from a diamond iron chest to one of the side faces of the Auto Chisel using Ender IO.  As soon as I put the diamond chisel into the chest the client and server crashed.  Here are the logs:
Client Crash Log: http://pastebin.com/KKKjs4ma
Server Crash Log: http://pastebin.com/QyZaF32b

Here are the versions of my mod pack that were directly interacting at the time of the crash:
Chisel 2: 2.4.1.40
Ender Core: 1.7.10-0.0.1.17_alpha
Ender IO: 1.7.10-2.3.0.407_beta
Iron Chest: 6.0.62.742

Edit 1:
This happens on a server and single player.  Looks to be tied to the reversion upgrade.  I added the recipe via MineTweaker which is how I got it without cheating too badly.

**Comment by TheCricket** [comment]
I will look at this tomorrow

**Comment by TheCricket** [comment]
done

**Comment by Drethic** [comment]
Thank you, do you have plans to make items, like the different chisels, feed smarter so the chisels drop into the chisel spot into the upper left spot?

Also, is there a way for me to download the code or is there another release planned in the before Saturday.

**Comment by TheCricket** [comment]
dev builds are available at http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10-Dev/ but remember. THEY ARE DEV BUILDS if something is wrong don't complain :P you signed up for it when downloading a dev build. idk when the next release build will be

**Comment by Namikon** [comment]
We just got the same problem with the latest chisel version: (2.5.1.44)
http://pastebin.com/N5T6rJF1

**Comment by TheCricket** [comment]
Are you sure, I tested this for a few hours
