### ISSUE TITLE
[Question] Where are all of the really cool mod blocks? [dev builds]

### ISSUE THREAD

**Issue by ate0ate** [Chisel-2/Chisel-2#393]
I haven't updated dev releases in a long time now since mod blocks were removed. There was some amazing blocks there and my builds rely heavily on them. Are they ever coming back or is chiselcompat ever going to be released? Maybe you could just keep the support for them the same for now until chiselcompat actually starts being developed? Sorry, I just really love those blocks:P

Either way, thanks for the great mod!

**Comment by TheCricket** [comment]
I know @Drullkus said he was going to put them back but if he didn't I will do that today

**Comment by TheCricket** [comment]
done
