### ISSUE TITLE
Something wrong with block cast

### ISSUE THREAD

**Issue by desertir** [Chisel-2/Chisel-2#399]
Client was crashed when I drop a sandstone block in Chisel GUI.
Versions of Forge is 10.13.4.1492 and Chisel 2 is 2.5.0.42.
Crash report: http://pastebin.com/xh0HAA38
I cant google this issue. Possible problem has been solved?

**Comment by desertir** [comment]
Oh, maybe I duplicated #395

**Comment by TheCricket** [comment]
you did...

**Comment by desertir** [comment]
Yep, work fine! I'm slowpoke. Sorry to trouble you :)
And thanx for amazing mod!
