### ISSUE TITLE
Dupe with Iron Bricks from Tinkers' Construct

### ISSUE THREAD

**Issue by Farthen** [Chisel-2/Chisel-2#402]
Chisel 2 can convert Tinkers' Construct Iron Bricks (and the 'fancy' alternative) to iron blocks. This is a problem because Tinkers' iron bricks are created with [just a single iron ingot and a Tinkers' Chisel](http://tinkers-construct.wikia.com/wiki/Chisel) (I have no idea why, it seems weird thinking about it but 'it's been that way forever' may be the appropriate explanation here). I don't really know if this is a Chisel or Tinkers' bug but as you can craft iron blocks back to ingots something needs to change here or there. It does use durability on both chisels but it is still a net win in iron ingots.

Forge version: 10.13.2.1291
Chisel 2 version: 2.3.9.36
Tinkers' Construct version: 1.8.3

**Comment by TheCricket** [comment]
You are way out of date... (on everything)  can you replicate it with the latest version

**Comment by Farthen** [comment]
You are totally correct - sorry, it seems to be fixed in a newer version.
