### ISSUE TITLE
java.lang.NoClassDefFoundError: team/chisel/Features

### ISSUE THREAD

**Issue by itanshi** [Chisel-2/Chisel-2#408]
2.5.0.43

http://pastebin.com/vzJmic7F

I'm assuming I did something dumb, but humor me a moment with the crash report. Thank you.

**Comment by TehNut** [comment]
1. This is a crash caused by ChiselFacades. Go there
2. This crash is caused because you are using Cricket's Chisel with a ChiselFacades version that only supports TeamChisel's Chisel.

**Comment by itanshi** [comment]
Thank you for the quick reply :D

**Comment by TehNut** [comment]
It even says in the filename of the mod that it's for ChiselTeam...

**Comment by Choonster** [comment]
For the record, there are separate versions of ChiselFacades for each fork of Chisel. You want a version with "cricket" in the name if you're using Cricket's Chisel 2 (this fork).

I explain it fairly thoroughly on the [CurseForge page](http://minecraft.curseforge.com/mc-mods/222784-chisel-facades).
