### ISSUE TITLE
Chisel2 spams the minecraft log

### ISSUE THREAD

**Issue by h404bi** [Chisel-2/Chisel-2#410]
It prints out many "false" value into the minecraft log when player using the chisel. For testing, I have narrowed mods to just Chisel2 mod.

![gif](https://cloud.githubusercontent.com/assets/5764917/9817665/e3d7ba5a-58d6-11e5-98af-10966905683c.gif)

**Comment by TheCricket** [comment]
What version are you using?

**Comment by h404bi** [comment]
@TheCricket Chisel2-2.5.0.43, with 1.7.10 forge 1448 or 1492.

**Comment by gabor6505** [comment]
I can also confirm this.
With the same version @h404bi mentioned, with Forge 1492 (1.7.10)

**Comment by TheCricket** [comment]
done
