### ISSUE TITLE
Arcane Stone Block Flickering/Transparent

### ISSUE THREAD

**Issue by Solace7** [Chisel-2/Chisel-2#411]
When using chisel 2.5.0 or 2.4.1 and chiseling arcane stone blocks to any variation. Placed blocks have flickering   or transparent textures.
![2015-09-12_10 26 37](https://cloud.githubusercontent.com/assets/9976088/9832719/d5f1b8ac-5938-11e5-8df8-944b98afbfec.png)

**Comment by Solace7** [comment]
![2015-09-12_10 26 23](https://cloud.githubusercontent.com/assets/9976088/9832731/f6ba6502-5938-11e5-818c-977d849f9067.png)

**Comment by TheCricket** [comment]
optifine?

**Comment by Solace7** [comment]
Removing optifine fixes transparent textures _bye bye optifine_

**Comment by TheCricket** [comment]
When in doubt get rid of optifine
