### ISSUE TITLE
Bug render chest

### ISSUE THREAD

**Issue by Bogdan-G** [Chisel-2/Chisel-2#97]
Hello. Use Chisel 2.2.1, graphic bug:
![image one](http://i.imgur.com/lNAHxTo.png)
More Images: http://imgur.com/a/jIfck

**Comment by CptSpaceToaster** [comment]
Hmmm... looks like there's a lot more to do here than what I expected.  You're going to have to hold off for a while anyways, while we sort out why they don't keep their inventories. 

Thank you for the bug report!  We'll get to it!

**Comment by TheCricket** [comment]
You should be able to place different colors next to each other, but not the same color

**Comment by CptSpaceToaster** [comment]
placing two different colored chests next to each other would allow them to combine into one of the colors... maybe THAT shouldn't be included...

**Comment by marky-b** [comment]
> ...while we sort out why they don't keep their inventories.

Is there a bug submitted for that particular issue. I just ran across it today (v2.2.1) and wanted to follow the progress, but didn't see any bugs listing it in particular.

Thanks

**Comment by warlordjones** [comment]
Fixed.
