### ISSUE TITLE
CTM Lighting bug

### ISSUE THREAD

**Issue by Aedaeum** [Chisel-2/Chisel-2#99]
For some reason any block that has CTM is causing these lighting issues.
![ctmissue](https://cloud.githubusercontent.com/assets/2054218/5614578/5745c8b4-94a7-11e4-84ac-f0348a71a6eb.png)

I have two friends, one friend with the same graphics card as me GTX 760, and another friend with an ATI card. My friend with the same graphics card as me is having the same issue. My friend with the ATI card is not. This was the only difference that we noticed. We're all using the exact same setup.

This issue is also only noticeable at night/in the dark. I am not using Optifine.
Thanks for you time.

**Comment by CptSpaceToaster** [comment]
I noticed some slight ghosting nastiness with the changes I made as well... Thank you for pointing it out.  I probably broke it.

**Comment by Aedaeum** [comment]
Thanks for the quick response. Glad to see this is fixable :)

**Comment by CptSpaceToaster** [comment]
Hmmmm...
I fixed torch light, but sunlight will still be problematic:
![partiallyfixed](http://i.imgur.com/EG2RDzx.jpg)

I pushed this fix for tomorrow's build.

**Comment by Aedaeum** [comment]
Excellent, thanks so much for your quick work :smile:

**Comment by Drullkus** [comment]
He's so good at lighting. 

He's so good he can make colors even 

Oh wait

**Comment by CptSpaceToaster** [comment]
**1st rule...**
1.) We don't talk about the first rule :)

**Comment by warlordjones** [comment]
2.) Remember Rule 1

**Comment by Drullkus** [comment]
3) I break all the rules. Especially Rule Numero Uno

**Comment by CptSpaceToaster** [comment]
So, the lighting artifacts at the bottom of the block remain as a mystery to me, and might indicate an odd rotation/problem in the CTM renderer.  For now, I think the problem is somewhat managable until I can take a close look at it.

**Comment by Aedaeum** [comment]
I believe those bottom glitches to simply be the bad coding in the Minecraft lighting engine. If I stick a torch on just regular stone or any other block for that matter (some more noticeable then others) I get that strange lighting at the bottom.

**Comment by CptSpaceToaster** [comment]
Good to know, however now that bugs me even more... Something has to be going on that limits the rendering engine that way, and I've never quite noticed this until now.

**Comment by Aedaeum** [comment]
I noticed that the CTM in optifine doesn't suffer this issue. I'm assuming because you're using a custom renderer, that these issues occur? I also assume that the CTM in Optifine simply rotates the textures around, using the standard renderer.

I was just curious, so I thought I'd ask :smile:

**Comment by CptSpaceToaster** [comment]
More or less... I have been busy elsewhere.

**Comment by warlordjones** [comment]
As far as I can see this is fixed.

**Comment by CptSpaceToaster** [comment]
Striping will occur if you look REALLY closely at the sunlight in caves... It's not very noticeable, but it's there.
